### ISSUE TITLE
The future of CNN Logger

### ISSUE THREAD

**Issue by jamsyoung** [cnnlabs/cnn-logger#12]
I **think** all Harbor managed docker containers automatically send all standard output to logz.io.
If that is the case, what value does CNN Logger provide?

**Do we need CNN Logger anymore?**
Thoughts?

 @MDrooker @mtcrutch @DrEnter @adslaton @niahmiah

**Comment by adslaton** [comment]
It is still needed for non-harbor apps? The tagging that this module provides seems to be beneficial.

**Comment by rwinbush** [comment]
We are using it as part of a middleware layer we wrote to log client-side log messages to logz.io.  The may benefit is the tagging like A.D. mentioned above.

**Comment by jamsyoung** [comment]
Ok, sounds like we def need to keep it alive.  Very good points @adslaton @rwinbush .

Going down the path where it turns into a client side logger (or server side for non-harbor hosted apps), does this package as it exists today meet the expectations? Are we re-inventing the wheel here?  Are there other things that are more targeted for client side logging that would work better?
